version: '3'

services:
  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_manager
    volumes:
      - /home/ubuntu/db-storage:/var/lib/mysql
  task-manager:
    image: jainendrakumar21/task-manager:latest
    container_name: task-manager-app
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
    restart: always
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=task_manager
      - DATABASE_PORT=3306
