version: '3'

services:
  nginx:
    image: nginx:1.17.9
    container_name: task-manager-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./whoops.html:/task-manager/whoops.html    
  mysql-db:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_manager
    volumes:
      - /home/ubuntu/db-storage:/var/lib/mysql
  spring-boot-task-manager-app:
    build: .
    depends_on:
      - nginx
      - mysql-db
    ports:
      - 8080
    restart: always
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=task_manager
      - DATABASE_PORT=3306
    
